### PR TITLE
Add OAuth URLs as `client_options`

### PR DESCRIPTION
**Pull request by amar47shah**
OAuth URLs for Ravelry are given [here](http://www.ravelry.com/api#authenticating).
Following examples for strategy configuration from [Netflix](https://github.com/stve/omniauth-netflix/blob/master/lib/omniauth/strategies/netflix.rb).

Specs added for options.

### CODE REVIEW

**Comment by duien** [comment]
Thanks for helping get this up to date! I tested out your changes and they look good, and updated the outdated request used by `raw_info` as well.

I was able to log in successfully in a tiny Rails app, so I think it should be all up-to-date with the current Ravelry API now!

**Comment by amar47shah** [comment]
Great! Is your tiny Rails app client on Github? I am brand new to OAuth and I could use some help seeing it in action.

**Comment by duien** [comment]
I didn't, but I went ahead and uploaded it. Here you go!

[duien/example-omniauth-ravelry](https://github.com/duien/example-omniauth-ravelry)

**Comment by amar47shah** [comment]
Thanks so much!

**Pull request merged**
